### ISSUE TITLE
Asymptote building

### ISSUE THREAD

**Issue by Nichodon** [Gunn-GAtM/gatm#20]
When trying to build, I often get this:

`freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect
This is quite likely caused by a bad '-display' parameter
freeglut (asy): fghInitialize: CreateDC failed, Screen size info may be incorrect`

I know that I am to expect "superfluous errors" but it's a little bit excessive.
Also building often takes up to a couple of minutes which makes it **_excruciatingly_** painful to edit the asymptote.

**Comment by Nichodon** [comment]
pls help

**Comment by ytchang05** [comment]
The build system was just updated, and an automatic workflow set up.  It is still untested on Windows/Linux as of now, but support is planning on being added on those platforms. For the build time, I don't think there's much that can be done on that...
