### ISSUE TITLE
Gray

### ISSUE THREAD

**Issue by Nichodon** [Gunn-GAtM/gatm#21]
Ok so I got a hold of the textbook for about 10 seconds (not sure if I'm allowed to take a copy given that I'm not taking Analysis and most of the teachers are unaware of my involvement!) and the light-gray row colors are not printed. Making the tables a lot uglier and harder to read. Oof.

There's some figures (at least one) with gray in them but I didn't get a chance to check them. In any case, this must be rectified!

**Comment by Nichodon** [comment]
The 3D figure in question printed fine, but extremely light. I think a good solution to this problem is to merely increase the darkness level of the table `light-gray`.

**Comment by Nichodon** [comment]
Would love to see some confirmation of this from people who have a current copy of the book! (not me, removing my assignment.)

**Comment by ytchang05** [comment]
This year (and I think likely for the future as well) GAtM will not be printed out and instead http://gunn-gatm.github.io will just be used in class, so this might no longer apply. @anematode thoughts?

**Comment by anematode** [comment]
Probably not an issue; grayscale should indeed work, although asy grayscale is bugged as of version 2.58, but the effect isn't major.

**Comment by qpwoeirut** [comment]
wait no that's now what i meant lol
That number 21 was supposed to reference the problem
