### ISSUE TITLE
[TYPO] Matrices are going in the wrong direction

### ISSUE THREAD

**Issue by SheepTester** [Gunn-GAtM/gatm#30]
https://github.com/anematode/gatm/blob/ad494de39068d117cceabdcdd52f16fb54f65699/comp_map/comp_map_source.tex#L55-L56

The problem says a rotation over line θ/2 then ϕ/2, but the matrices, which go right to left, show a transformation relative to ϕ then a transformation relative to θ

**Comment by SheepTester** [comment]
Reported by Ms. Tantod, according to @Velosify

**Comment by ytchang05** [comment]
I believe this is now fixed.

**Comment by SheepTester** [comment]
Xie xie kind stranger!
