### ISSUE TITLE
[TYPO] Drawing commands show up in text

### ISSUE THREAD

**Issue by SheepTester** [Gunn-GAtM/gatm#32]
https://github.com/anematode/gatm/blob/ad494de39068d117cceabdcdd52f16fb54f65699/comp_map/comp_map_answers.tex#L481-L485

Epic drawing commands show up in text

![image](https://user-images.githubusercontent.com/22133785/76134214-80af5800-5fd1-11ea-8935-9bda40e95683.png)

**Comment by ytchang05** [comment]
I believe this issue is no longer present in the most recent build (not sure at what point it was fixed).
