### ISSUE TITLE
[TYPO] Problems 11 and 12 in answer key seem to be part of a different numbering scheme

### ISSUE THREAD

**Issue by SheepTester** [Gunn-GAtM/gatm#33]
https://github.com/anematode/gatm/blob/master/comp_map/comp_map_answers.tex#L990

![image](https://user-images.githubusercontent.com/22133785/76134277-de43a480-5fd1-11ea-9bde-77ddbda6860a.png)

Of note in the above screenshot:

- Problem 9 is bolded properly, but it actually is the answer to problem 10.

- Problem 1 is the answer to problem 11 and is not bolded

- Figure 5 innocently references problem 2, which has the answer to problem 12

**Comment by Nichodon** [comment]
These sorts of continuity issues arise because I only updated the first five chapters of the answer key, so this might take a while.

**Comment by SheepTester** [comment]
Scary

**Comment by ytchang05** [comment]
I believe that this has been fixed in some past commit, and is no longer present in the newest build.
