### ISSUE TITLE
[TYPO] Denominator should be 4

### ISSUE THREAD

**Issue by SheepTester** [Gunn-GAtM/gatm#34]
https://github.com/anematode/gatm/blob/ad494de39068d117cceabdcdd52f16fb54f65699/comp_map/comp_map_answers.tex#L678

![dfgdfg](https://cdn.discordapp.com/attachments/500124272715366440/685658056432156727/fSHLxGAh8P8AOTykLJiBcwIAAAAASUVORK5CYII.png)

First row, second column should be over 4 I think

**Comment by ytchang05** [comment]
I believe this issue is no longer present in the most recent build (not sure at what point it was fixed).

**Comment by SheepTester** [comment]
Thank you, Uwu xian sheng!
