### ISSUE TITLE
[TYPO] Forgotten negative sign

### ISSUE THREAD

**Issue by SheepTester** [Gunn-GAtM/gatm#35]
https://github.com/anematode/gatm/blob/ad494de39068d117cceabdcdd52f16fb54f65699/comp_map/comp_map_answers.tex#L761

![discord canno righ click copy angry](https://cdn.discordapp.com/attachments/500124272715366440/685658994852757524/KTgsI4mV0V7zP8DdldK2hzSCrQAAAAASUVORK5CYII.png)

Equation has `-cos theta` in the second row, second column, but the corresponding cell in the other matrix is positive.

Also, why are the matrix brackets round? lol

**Comment by SheepTester** [comment]
Since I'm here, here's some other comments I'm not sure if they deserve an issue:

---

https://github.com/anematode/gatm/blob/ad494de39068d117cceabdcdd52f16fb54f65699/comp_map/comp_map_answers.tex#L650

![screenie](https://cdn.discordapp.com/attachments/500124272715366440/685657524749336637/VtYteL0WTjKXoTR6v8VXTgIm5ExPmFen3xzhqylZKoYwmW8uGP8HlUEzwBKIYcMAAAAASUVORK5CYII.png)

I disagree here since I think stretches imply a positive stretch factor, so they can't be used to reflect. Especially since here 

https://github.com/anematode/gatm/blob/master/comp_map/comp_map_answers.tex#L1054-L1058

says that reflections are necessary to flip orientation.

---

https://github.com/anematode/gatm/blob/ad494de39068d117cceabdcdd52f16fb54f65699/comp_map/comp_map_answers.tex#L1096-L1133

![righ click werehgudsfgydfs discord angery](https://cdn.discordapp.com/attachments/500124272715366440/685660856951767051/AfyYQWPhkeoUAAAAAElFTkSuQmCC.png)

I don't think "scale" is a good word to use here because "scale" could be "dilate" or "stretch," but even a stretch in the direction of <c, d> would change the <a, b> vector I think. Perhaps the <c, d> vector could get scaled, or the parallelogram gets l e n g t h e n e d

**Comment by ytchang05** [comment]
The negative sign has been un-dropped in 9f10b9e222fa832e1bc9a7e451af1cb9c59b58aa, the other comments in this issue I will leave to @anematode .

**Comment by anematode** [comment]
anematode
