### ISSUE TITLE
[TYPO] 1/12 * 8 is not 3/4

### ISSUE THREAD

**Issue by SheepTester** [Gunn-GAtM/gatm#36]
https://github.com/anematode/gatm/blob/3a381a252699938ea0672871926193ec68aaa464/comp_map/comp_map_answers.tex#L1445

![dfg](https://cdn.discordapp.com/attachments/500124272715366440/687340008008319134/HEEmCKKkOwzQd4Og06vXTXaEf7BLRx7QJTTm20kVqfWIUw2rFv7hhzje5jW3fChjh5GTV30iB9O14RmatbHniAQuZCuUQJAEGQjw.png)

Top right row in product should be 2/3. Rest of the matrices may need updating

\cc @Velosify

**Comment by ytchang05** [comment]
I believe this issue is no longer present in the most recent build (not sure at what point it was fixed).

**Comment by SheepTester** [comment]
Thank you uwu!

**Comment by anematode** [comment]
UwU
