### ISSUE TITLE
[TYPO] Grammar (pg 33)

### ISSUE THREAD

**Issue by Nichodon** [Gunn-GAtM/gatm#38]
As reported by the Mr. Thomas Li, the question on the reflection matrix part (d) has bad grammar.

**Comment by anematode** [comment]
A haiku to match:

I read the question;
Soul-searching, I do wonder,
What does Thomas mean?

**Comment by ytchang05** [comment]
In the most recent build, it seems that the grammar for this problem is alright, so I will be closing this issue.
